language: java
matrix:
  include:
    - jdk: oraclejdk8

script: >-
    ./config/travis/run-checks.sh &&
    travis_retry ./gradlew clean checkstyleMain checkstyleTest headless allTests coverage coveralls

before_install:
- chmod +x travis/check-trailing-whitespace.sh
- chmod +x travis/run-checks.sh
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"

addons:
  apt:
    packages:
      - oracle-java8-installer
